# Site settings
title: Justin's Notes
email: JustinRolston at gmail
username: JustinRolston
description: "I want to share stuff that I hacked, struggled, and defeated.  I would like give some nuggets of info that would safe other time."
baseurl: ""
url: "http://JustinRolston.github.io"

# Build settings
markdown: kramdown
permalink: pretty
